# Basic analysis

In [23]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [24]:
df = pd.read_csv("/home/jawad/my_jupyter_env/Data_Science_Projects/agricultural_water_efficiency/agricultural_water_efficiency_10000.csv")

In [25]:
df.head()

,Date,Region,Crop_Type,Temperature_C,Rainfall_mm,Irrigation_mm,Water_Used_Liters,Area_Hectares,Crop_Yield_Tons,Soil_Moisture_Percent,Irrigation_Method
0,2018-08-28,Buner,Wheat,11.7,86.2,254.0,25208820,7.41,17.64,44.0,Sprinkler
1,2024-09-04,Charsadda,Maize,19.1,193.4,248.8,4289340,0.97,5.69,59.1,Drip
2,2021-08-30,Peshawar,Sugarcane,18.0,39.8,214.6,20682720,8.13,311.62,41.9,Sprinkler
3,2024-12-05,Mardan,Wheat,20.3,164.8,237.4,37404600,9.30,27.34,58.9,Flood
4,2020-11-26,Mardan,Wheat,27.1,36.2,263.2,27245400,9.10,21.93,30.4,Sprinkler

In [26]:
# which region occure the most in the data ?
most_occuring_region = df["Region"].mode()
print("most occuring region in the data " ,most_occuring_region)

# highest temprature 
high_temp = df["Temperature_C"].max()
print("high temperature in celcius : ",high_temp)

# lowest temperature 
low_Temp = df["Temperature_C"].min()
print("lowest Temprature in Celcius : ", low_Temp)
print("__"*45)

# high temperature Region 
idx = df["Temperature_C"].idxmax()
print("Region with highest temperature:", df.loc[idx, "Region"])
print("Highest temperature:", df.loc[idx, "Temperature_C"])
print("__" * 45)
# Average temperature 
avg_temp = df["Temperature_C"].mean()
print("Average temperature : ", avg_temp)

# lowest temprature recorded area 
idx = df["Temperature_C"].idxmin()
print("Region with the lowest temperature : ",df.loc[idx,"Region"])
print("lowest temperature : ",df.loc[idx,"Temperature_C"])

most occuring region in the data  0    Swat
Name: Region, dtype: str
high temperature in celcius :  44.0
lowest Temprature in Celcius :  5.0
__________________________________________________________________________________________
Region with highest temperature: Charsadda
Highest temperature: 44.0
__________________________________________________________________________________________
Average temperature :  24.96753
Region with the lowest temperature :  Swat
lowest temperature :  5.0

In [27]:
# average rainfall 
avg_rainfall = df["Rainfall_mm"].mean()
print("Average rainfall in milli meter : ", avg_rainfall.round(4))

# highest rainfall in milli meter 
high_rainfall_mm = df["Rainfall_mm"].max()
print("highest rainfall in milli meter : ", high_rainfall_mm)

# lowest rainfall in milli meter 
low_Rainfall_mm = df["Rainfall_mm"].min()
print("lowest rainfall in milli meter : ", low_Rainfall_mm)
print("__"* 45)

# rainfall by region 
rainfall_by_reg = df.groupby("Region")["Rainfall_mm"].mean()
print("\nRainfall by region :\n", rainfall_by_reg,4)
print("__" * 45)

# Average irrigation 
avg_irrigation = df["Irrigation_mm"].mean()
print("\nAverage Irrigation : ", avg_irrigation)

# high irrigation in milli meter
high_irrigation = df["Irrigation_mm"].max()
print("high irrigation in milli meter : ", high_irrigation)

# low irrigation in milli meter 
low_irrigation = df["Irrigation_mm"].min()
print("low irrigation in milli meter : ",low_irrigation)
print("__" * 45)
# high  irrigation recorded region 
idx = df["Irrigation_mm"].idxmax()
print("\nRegion recorded high irrigation in millimeter : ",df.loc[idx,"Region"])
print("highest irrigation in milli meter : ", df.loc[idx,"Irrigation_mm"])

# lowest irrigation recorded region 
idx = df["Irrigation_mm"].idxmin()
print("\nlowest irrigation recorded region : ", df.loc[idx,"Region"])
print("lowest irrigation in milli meter : ", df.loc[idx,"Irrigation_mm"])

Average rainfall in milli meter :  60.7296
highest rainfall in milli meter :  260.0
lowest rainfall in milli meter :  0.2
__________________________________________________________________________________________

Rainfall by region :
 Region
Buner        59.907181
Charsadda    60.675815
Dir          60.739345
Mardan       61.770438
Peshawar     61.062379
Swat         60.250968
Name: Rainfall_mm, dtype: float64 4
__________________________________________________________________________________________

Average Irrigation :  223.6711189516129
high irrigation in milli meter :  420.0
low irrigation in milli meter :  40.0
__________________________________________________________________________________________

Region recorded high irrigation in millimeter :  Dir
highest irrigation in milli meter :  420.0

lowest irrigation recorded region :  Peshawar
lowest irrigation in milli meter :  40.0

In [28]:
# average of the water used in liters columns 
avg_water_used = df["Water_Used_Liters"].mean()
print("Average water used in liters : ", avg_water_used)

# median of water used in liters 
median_water_used = df["Water_Used_Liters"].median()
print("Median of water consumption : ", median_water_used)

# maximum water used in liters 
max_water_used = df["Water_Used_Liters"].max()
print("Maximum water used in liters : ",max_water_used)

# minimum water used in liter
min_water_used = df["Water_Used_Liters"].min()
print("Minimum water used in liters : ",min_water_used)
print("__"* 45)

# In which region used the most water used in liters 
idx = df["Water_Used_Liters"].idxmax()
print("\nRegion in which most water used in liters : ", df.loc[idx,"Region"])
print("How many liters water used in peshawar : ", df.loc[idx,"Water_Used_Liters"])

# In which region used the minimum water 
idx = df["Water_Used_Liters"].idxmin()
print("Region in which minumum water is used in liters : ", df.loc[idx,"Region"])
print("How many liters water used in Dir : ",df.loc[idx,"Water_Used_Liters"])

Average water used in liters :  17734517.893
Median of water consumption :  16267260.0
Maximum water used in liters :  65729700
Minimum water used in liters :  394880
__________________________________________________________________________________________

Region in which most water used in liters :  Peshawar
How many liters water used in peshawar :  65729700
Region in which minumum water is used in liters :  Dir
How many liters water used in Dir :  394880

In [29]:
# average area hectares
avg_area_hectares = df["Area_Hectares"].mean()
print("Average of the Area Hectares : ", avg_area_hectares.round(2))

# maximum area 
max_area = df["Area_Hectares"].max()
print("Maximum Area in Hectares : ", max_area)

# minimum area 
min_area = df["Area_Hectares"].min()
print("Minimum area in Heactares : ", min_area)

Average of the Area Hectares :  6.24
Maximum Area in Hectares :  12.0
Minimum area in Heactares :  0.5

# Detecting outliers in the columns

In [30]:
df.head(2)

,Date,Region,Crop_Type,Temperature_C,Rainfall_mm,Irrigation_mm,Water_Used_Liters,Area_Hectares,Crop_Yield_Tons,Soil_Moisture_Percent,Irrigation_Method
0,2018-08-28,Buner,Wheat,11.7,86.2,254.0,25208820,7.41,17.64,44.0,Sprinkler
1,2024-09-04,Charsadda,Maize,19.1,193.4,248.8,4289340,0.97,5.69,59.1,Drip

In [31]:
# Detecting outliers in the temprature columns 
outliers = []
def detect_outliers(df):
    threshold = 3 
    mean = np.mean(df)
    std = np.std(df)
    for i in df:
        Z_score = (i - mean)/ std
        if np.abs(Z_score > threshold):
            outliers.append(i)
    return outliers
outliers_in_Temperature_C = detect_outliers(df["Temperature_C"])
print("there are no outliers in the Temperatures Columns : ",outliers)
print("__"*50)

# Detecting outliers in the Rainfall column using Z score 
outliers_in_Rainfall = detect_outliers(df["Rainfall_mm"])
print("\nOutliers in the rainfall data  :",outliers) 
print("total outliers in the rainfall data is : ",np.size(outliers_in_Rainfall))
print("__"*50)


# detecting outliers in the  Irrigation_mm 
outlier_in_irrigation = detect_outliers(df["Irrigation_mm"])
print("\noutliers in the  irrigation data : ",outlier_in_irrigation)
print("total number of outliers in the irrigation data : ",np.size(outlier_in_irrigation))
print("__"*50)



# detecting outliers in the water used in liters  
outliers_in_water_used = detect_outliers(df["Water_Used_Liters"])
print("\noutliers in the water used in liters data : ", outliers_in_water_used)
print("Total number of outliers in water used in liters : ",np.size(outliers_in_water_used))
print("__"*50)


# detecting outliers in the Area Hectares
outlier_in_Area = detect_outliers(df["Area_Hectares"])
print("\noutliers in the  Area Hectares data : ",outlier_in_Area)
print("Total number of outliers in Area Hectares : ", np.size(outlier_in_Area))
print("__"*50)


# detecting outliers in the Crop yeild tons 
outlier_in_Crop_Yield_Tons = detect_outliers(df["Crop_Yield_Tons"])
print("\noutliers in the  Crop_Yield_Tons data : ",outlier_in_Crop_Yield_Tons)
print("Total number of outliers in Crop_Yield_Tons : ", np.size(outlier_in_Crop_Yield_Tons))
print("__"*50)


# detecting outliers in the soil moisture percent 
outlier_in_Soil_Moisture_Percent = detect_outliers(df["Soil_Moisture_Percent"])
print("\noutliers in the  Soil_Moisture_Percent : ",outlier_in_Soil_Moisture_Percent)
print("Total number of outliers in Soil_Moisture_Percent : ", np.size(outlier_in_Soil_Moisture_Percent))
print("__"*50)

there are no outliers in the Temperatures Columns :  []
____________________________________________________________________________________________________

Outliers in the rainfall data  : [193.4, 239.7, 197.8, 222.7, 238.3, 204.5, 184.7, 184.4, 220.1, 197.1, 194.7, 195.4, 204.9, 185.3, 241.4, 207.3, 213.9, 186.1, 207.5, 235.1, 184.3, 239.3, 183.5, 220.0, 249.3, 226.6, 183.8, 204.5, 203.3, 213.1, 183.8, 191.9, 232.6, 214.4, 195.1, 194.0, 260.0, 200.9, 203.7, 191.2, 209.0, 230.7, 257.5, 189.4, 184.8, 187.3, 184.6, 188.7, 188.7, 236.0, 194.2, 195.0, 223.8, 202.1, 192.8, 221.3, 215.8, 212.7, 189.5, 214.4, 260.0, 237.3, 187.3, 185.4, 202.5, 183.3, 218.6, 218.5, 190.4, 183.4, 215.0, 201.0, 205.1, 231.4, 242.9, 186.3, 256.2, 193.7, 185.8, 188.1, 195.7, 196.9, 260.0, 189.3, 197.5, 186.2, 201.3, 183.1, 260.0, 183.6, 205.3, 187.4, 182.8, 190.5, 182.9, 189.7, 218.9, 187.9, 248.8, 235.0, 199.5, 206.6, 241.7, 188.0, 212.8, 194.3, 203.8, 187.7, 260.0, 194.4, 189.9, 218.3, 260.0, 183.0, 183.4, 208.8, 190.7, 190.1, 212.5, 260.0, 197.5, 194.4, 216.1, 183.8, 192.6, 194.1, 187.7, 223.2, 184.7, 253.9, 260.0, 185.4, 226.9, 260.0, 190.3, 260.0, 184.1, 204.1, 215.0, 204.9]
total outliers in the rainfall data is :  140
____________________________________________________________________________________________________

outliers in the  irrigation data :  [193.4, 239.7, 197.8, 222.7, 238.3, 204.5, 184.7, 184.4, 220.1, 197.1, 194.7, 195.4, 204.9, 185.3, 241.4, 207.3, 213.9, 186.1, 207.5, 235.1, 184.3, 239.3, 183.5, 220.0, 249.3, 226.6, 183.8, 204.5, 203.3, 213.1, 183.8, 191.9, 232.6, 214.4, 195.1, 194.0, 260.0, 200.9, 203.7, 191.2, 209.0, 230.7, 257.5, 189.4, 184.8, 187.3, 184.6, 188.7, 188.7, 236.0, 194.2, 195.0, 223.8, 202.1, 192.8, 221.3, 215.8, 212.7, 189.5, 214.4, 260.0, 237.3, 187.3, 185.4, 202.5, 183.3, 218.6, 218.5, 190.4, 183.4, 215.0, 201.0, 205.1, 231.4, 242.9, 186.3, 256.2, 193.7, 185.8, 188.1, 195.7, 196.9, 260.0, 189.3, 197.5, 186.2, 201.3, 183.1, 260.0, 183.6, 205.3, 187.4, 182.8, 190.5, 182.9, 189.7, 218.9, 187.9, 248.8, 235.0, 199.5, 206.6, 241.7, 188.0, 212.8, 194.3, 203.8, 187.7, 260.0, 194.4, 189.9, 218.3, 260.0, 183.0, 183.4, 208.8, 190.7, 190.1, 212.5, 260.0, 197.5, 194.4, 216.1, 183.8, 192.6, 194.1, 187.7, 223.2, 184.7, 253.9, 260.0, 185.4, 226.9, 260.0, 190.3, 260.0, 184.1, 204.1, 215.0, 204.9]
total number of outliers in the irrigation data :  140
____________________________________________________________________________________________________

outliers in the water used in liters data :  [193.4, 239.7, 197.8, 222.7, 238.3, 204.5, 184.7, 184.4, 220.1, 197.1, 194.7, 195.4, 204.9, 185.3, 241.4, 207.3, 213.9, 186.1, 207.5, 235.1, 184.3, 239.3, 183.5, 220.0, 249.3, 226.6, 183.8, 204.5, 203.3, 213.1, 183.8, 191.9, 232.6, 214.4, 195.1, 194.0, 260.0, 200.9, 203.7, 191.2, 209.0, 230.7, 257.5, 189.4, 184.8, 187.3, 184.6, 188.7, 188.7, 236.0, 194.2, 195.0, 223.8, 202.1, 192.8, 221.3, 215.8, 212.7, 189.5, 214.4, 260.0, 237.3, 187.3, 185.4, 202.5, 183.3, 218.6, 218.5, 190.4, 183.4, 215.0, 201.0, 205.1, 231.4, 242.9, 186.3, 256.2, 193.7, 185.8, 188.1, 195.7, 196.9, 260.0, 189.3, 197.5, 186.2, 201.3, 183.1, 260.0, 183.6, 205.3, 187.4, 182.8, 190.5, 182.9, 189.7, 218.9, 187.9, 248.8, 235.0, 199.5, 206.6, 241.7, 188.0, 212.8, 194.3, 203.8, 187.7, 260.0, 194.4, 189.9, 218.3, 260.0, 183.0, 183.4, 208.8, 190.7, 190.1, 212.5, 260.0, 197.5, 194.4, 216.1, 183.8, 192.6, 194.1, 187.7, 223.2, 184.7, 253.9, 260.0, 185.4, 226.9, 260.0, 190.3, 260.0, 184.1, 204.1, 215.0, 204.9, 55005960, 56849640, 53336400, 53136000, 51523680, 61844900, 59498850, 52595610, 53844800, 52998400, 61229780, 54447960, 53439750, 52753120, 65729700, 60940580, 51109680, 57445920, 54177310, 53726400, 52376100, 51492780, 54315400, 51456000, 50862000, 54143040, 52508160, 54137640, 56773350, 57259440, 56116320, 62268000, 56373000, 52122480, 55134060, 55135500, 50804700, 51601400]
Total number of outliers in water used in liters :  178
____________________________________________________________________________________________________

outliers in the  Area Hectares data :  [193.4, 239.7, 197.8, 222.7, 238.3, 204.5, 184.7, 184.4, 220.1, 197.1, 194.7, 195.4, 204.9, 185.3, 241.4, 207.3, 213.9, 186.1, 207.5, 235.1, 184.3, 239.3, 183.5, 220.0, 249.3, 226.6, 183.8, 204.5, 203.3, 213.1, 183.8, 191.9, 232.6, 214.4, 195.1, 194.0, 260.0, 200.9, 203.7, 191.2, 209.0, 230.7, 257.5, 189.4, 184.8, 187.3, 184.6, 188.7, 188.7, 236.0, 194.2, 195.0, 223.8, 202.1, 192.8, 221.3, 215.8, 212.7, 189.5, 214.4, 260.0, 237.3, 187.3, 185.4, 202.5, 183.3, 218.6, 218.5, 190.4, 183.4, 215.0, 201.0, 205.1, 231.4, 242.9, 186.3, 256.2, 193.7, 185.8, 188.1, 195.7, 196.9, 260.0, 189.3, 197.5, 186.2, 201.3, 183.1, 260.0, 183.6, 205.3, 187.4, 182.8, 190.5, 182.9, 189.7, 218.9, 187.9, 248.8, 235.0, 199.5, 206.6, 241.7, 188.0, 212.8, 194.3, 203.8, 187.7, 260.0, 194.4, 189.9, 218.3, 260.0, 183.0, 183.4, 208.8, 190.7, 190.1, 212.5, 260.0, 197.5, 194.4, 216.1, 183.8, 192.6, 194.1, 187.7, 223.2, 184.7, 253.9, 260.0, 185.4, 226.9, 260.0, 190.3, 260.0, 184.1, 204.1, 215.0, 204.9, 55005960, 56849640, 53336400, 53136000, 51523680, 61844900, 59498850, 52595610, 53844800, 52998400, 61229780, 54447960, 53439750, 52753120, 65729700, 60940580, 51109680, 57445920, 54177310, 53726400, 52376100, 51492780, 54315400, 51456000, 50862000, 54143040, 52508160, 54137640, 56773350, 57259440, 56116320, 62268000, 56373000, 52122480, 55134060, 55135500, 50804700, 51601400]
Total number of outliers in Area Hectares :  178
____________________________________________________________________________________________________

outliers in the  Crop_Yield_Tons data :  [193.4, 239.7, 197.8, 222.7, 238.3, 204.5, 184.7, 184.4, 220.1, 197.1, 194.7, 195.4, 204.9, 185.3, 241.4, 207.3, 213.9, 186.1, 207.5, 235.1, 184.3, 239.3, 183.5, 220.0, 249.3, 226.6, 183.8, 204.5, 203.3, 213.1, 183.8, 191.9, 232.6, 214.4, 195.1, 194.0, 260.0, 200.9, 203.7, 191.2, 209.0, 230.7, 257.5, 189.4, 184.8, 187.3, 184.6, 188.7, 188.7, 236.0, 194.2, 195.0, 223.8, 202.1, 192.8, 221.3, 215.8, 212.7, 189.5, 214.4, 260.0, 237.3, 187.3, 185.4, 202.5, 183.3, 218.6, 218.5, 190.4, 183.4, 215.0, 201.0, 205.1, 231.4, 242.9, 186.3, 256.2, 193.7, 185.8, 188.1, 195.7, 196.9, 260.0, 189.3, 197.5, 186.2, 201.3, 183.1, 260.0, 183.6, 205.3, 187.4, 182.8, 190.5, 182.9, 189.7, 218.9, 187.9, 248.8, 235.0, 199.5, 206.6, 241.7, 188.0, 212.8, 194.3, 203.8, 187.7, 260.0, 194.4, 189.9, 218.3, 260.0, 183.0, 183.4, 208.8, 190.7, 190.1, 212.5, 260.0, 197.5, 194.4, 216.1, 183.8, 192.6, 194.1, 187.7, 223.2, 184.7, 253.9, 260.0, 185.4, 226.9, 260.0, 190.3, 260.0, 184.1, 204.1, 215.0, 204.9, 55005960, 56849640, 53336400, 53136000, 51523680, 61844900, 59498850, 52595610, 53844800, 52998400, 61229780, 54447960, 53439750, 52753120, 65729700, 60940580, 51109680, 57445920, 54177310, 53726400, 52376100, 51492780, 54315400, 51456000, 50862000, 54143040, 52508160, 54137640, 56773350, 57259440, 56116320, 62268000, 56373000, 52122480, 55134060, 55135500, 50804700, 51601400, 491.32, 514.26, 561.17, 784.11, 387.39, 418.09, 368.11, 492.15, 466.34, 535.25, 542.89, 443.54, 464.26, 484.14, 366.32, 345.5, 350.53, 365.95, 391.0, 434.33, 466.0, 460.22, 414.15, 509.01, 466.64, 517.85, 362.84, 711.85, 458.0, 369.36, 466.86, 739.58, 449.88, 431.52, 475.01, 430.53, 378.76, 348.45, 516.6, 364.26, 409.49, 652.0, 382.09, 351.51, 704.85, 373.81, 410.16, 365.18, 365.86, 354.64, 558.42, 517.87, 503.17, 536.11, 419.25, 499.01, 472.27, 393.92, 439.66, 389.98, 453.73, 379.33, 414.08, 512.48, 596.54, 497.27, 360.88, 407.06, 431.66, 434.19, 706.38, 472.66, 811.7, 565.51, 451.49, 402.28, 519.67, 337.4, 528.62, 415.17, 334.86, 575.71, 338.67, 478.65, 351.74, 660.46, 461.43, 523.11, 387.55, 521.48, 363.24, 365.61, 549.18, 356.97, 397.49, 379.53, 347.75, 493.92, 380.89, 458.03, 389.91, 388.96, 362.52, 477.11, 626.72, 474.4, 358.06, 372.6, 387.96, 539.39, 566.59, 420.96, 337.7, 395.19, 420.27, 673.17, 485.77, 402.61, 548.12, 377.57, 503.98, 507.33, 425.09, 477.48, 707.59, 377.84, 479.21, 338.76, 414.62, 474.14, 848.07, 373.02, 484.05, 423.57, 590.13, 487.1, 535.56, 550.7, 422.14, 370.41, 364.78, 368.34, 607.88, 495.38, 428.88, 465.66, 506.26, 450.88, 493.08, 470.8, 577.31, 367.63, 519.41, 376.23, 474.07, 529.09, 605.22, 336.6, 374.43, 409.62, 353.96, 355.1, 335.34, 419.99, 417.41, 453.07, 382.77, 775.23, 364.32, 414.44, 480.72, 387.64, 706.11, 517.69, 390.06, 584.81, 375.21, 333.69, 718.88, 747.86, 470.5, 553.11, 499.46, 707.9, 358.31, 484.18, 478.2, 449.53, 558.5, 432.28, 456.6, 696.2, 431.9, 346.64, 463.7, 441.32, 502.95, 568.39, 366.83, 408.03, 507.52, 779.73, 348.62, 391.21, 436.93, 565.06, 476.37, 527.42, 408.64, 551.25, 345.7, 335.79, 375.71, 563.82, 347.72, 444.88, 367.72, 478.56, 407.1, 547.7, 374.96, 342.95, 353.91, 581.06, 539.09, 372.27, 470.25, 479.84, 387.48, 367.99, 375.14, 480.49, 517.9, 500.71, 335.19, 530.95, 468.93, 432.76, 445.32, 601.91, 512.16, 739.48, 379.98, 333.85, 338.52, 546.32, 425.55, 496.77, 397.84, 387.5, 575.29, 522.49, 350.06, 567.31, 344.18, 368.73, 382.51, 400.75, 354.94, 455.94, 395.2, 335.05, 363.11, 503.14, 699.15, 525.71, 351.74, 339.52, 379.02, 457.25, 358.15, 529.02, 371.08, 602.66, 382.42, 440.42, 559.26, 375.97, 400.63, 460.56, 458.57, 437.11, 380.08, 386.92, 489.45, 470.73, 473.06, 349.39, 404.51, 411.7, 390.16, 355.17, 348.27, 528.87, 478.6, 496.17, 364.44, 432.53, 352.31, 428.84, 365.27, 384.56, 500.75, 442.33, 334.31, 516.03, 527.36, 443.3, 473.38, 352.42, 414.38, 347.63, 477.75, 445.02, 409.03, 533.19, 369.33, 349.17, 566.37, 503.41, 410.66, 379.87, 345.47, 478.57, 654.46, 349.56, 441.26, 394.46, 394.55, 366.84, 378.16, 528.05, 388.19, 638.12, 401.87, 377.07, 499.62, 379.64, 542.67, 454.41, 381.79, 419.49, 344.32, 502.44, 701.38, 357.2, 493.76, 404.21, 420.25, 373.73, 481.57]
Total number of outliers in Crop_Yield_Tons :  529
____________________________________________________________________________________________________

outliers in the  Soil_Moisture_Percent :  [193.4, 239.7, 197.8, 222.7, 238.3, 204.5, 184.7, 184.4, 220.1, 197.1, 194.7, 195.4, 204.9, 185.3, 241.4, 207.3, 213.9, 186.1, 207.5, 235.1, 184.3, 239.3, 183.5, 220.0, 249.3, 226.6, 183.8, 204.5, 203.3, 213.1, 183.8, 191.9, 232.6, 214.4, 195.1, 194.0, 260.0, 200.9, 203.7, 191.2, 209.0, 230.7, 257.5, 189.4, 184.8, 187.3, 184.6, 188.7, 188.7, 236.0, 194.2, 195.0, 223.8, 202.1, 192.8, 221.3, 215.8, 212.7, 189.5, 214.4, 260.0, 237.3, 187.3, 185.4, 202.5, 183.3, 218.6, 218.5, 190.4, 183.4, 215.0, 201.0, 205.1, 231.4, 242.9, 186.3, 256.2, 193.7, 185.8, 188.1, 195.7, 196.9, 260.0, 189.3, 197.5, 186.2, 201.3, 183.1, 260.0, 183.6, 205.3, 187.4, 182.8, 190.5, 182.9, 189.7, 218.9, 187.9, 248.8, 235.0, 199.5, 206.6, 241.7, 188.0, 212.8, 194.3, 203.8, 187.7, 260.0, 194.4, 189.9, 218.3, 260.0, 183.0, 183.4, 208.8, 190.7, 190.1, 212.5, 260.0, 197.5, 194.4, 216.1, 183.8, 192.6, 194.1, 187.7, 223.2, 184.7, 253.9, 260.0, 185.4, 226.9, 260.0, 190.3, 260.0, 184.1, 204.1, 215.0, 204.9, 55005960, 56849640, 53336400, 53136000, 51523680, 61844900, 59498850, 52595610, 53844800, 52998400, 61229780, 54447960, 53439750, 52753120, 65729700, 60940580, 51109680, 57445920, 54177310, 53726400, 52376100, 51492780, 54315400, 51456000, 50862000, 54143040, 52508160, 54137640, 56773350, 57259440, 56116320, 62268000, 56373000, 52122480, 55134060, 55135500, 50804700, 51601400, 491.32, 514.26, 561.17, 784.11, 387.39, 418.09, 368.11, 492.15, 466.34, 535.25, 542.89, 443.54, 464.26, 484.14, 366.32, 345.5, 350.53, 365.95, 391.0, 434.33, 466.0, 460.22, 414.15, 509.01, 466.64, 517.85, 362.84, 711.85, 458.0, 369.36, 466.86, 739.58, 449.88, 431.52, 475.01, 430.53, 378.76, 348.45, 516.6, 364.26, 409.49, 652.0, 382.09, 351.51, 704.85, 373.81, 410.16, 365.18, 365.86, 354.64, 558.42, 517.87, 503.17, 536.11, 419.25, 499.01, 472.27, 393.92, 439.66, 389.98, 453.73, 379.33, 414.08, 512.48, 596.54, 497.27, 360.88, 407.06, 431.66, 434.19, 706.38, 472.66, 811.7, 565.51, 451.49, 402.28, 519.67, 337.4, 528.62, 415.17, 334.86, 575.71, 338.67, 478.65, 351.74, 660.46, 461.43, 523.11, 387.55, 521.48, 363.24, 365.61, 549.18, 356.97, 397.49, 379.53, 347.75, 493.92, 380.89, 458.03, 389.91, 388.96, 362.52, 477.11, 626.72, 474.4, 358.06, 372.6, 387.96, 539.39, 566.59, 420.96, 337.7, 395.19, 420.27, 673.17, 485.77, 402.61, 548.12, 377.57, 503.98, 507.33, 425.09, 477.48, 707.59, 377.84, 479.21, 338.76, 414.62, 474.14, 848.07, 373.02, 484.05, 423.57, 590.13, 487.1, 535.56, 550.7, 422.14, 370.41, 364.78, 368.34, 607.88, 495.38, 428.88, 465.66, 506.26, 450.88, 493.08, 470.8, 577.31, 367.63, 519.41, 376.23, 474.07, 529.09, 605.22, 336.6, 374.43, 409.62, 353.96, 355.1, 335.34, 419.99, 417.41, 453.07, 382.77, 775.23, 364.32, 414.44, 480.72, 387.64, 706.11, 517.69, 390.06, 584.81, 375.21, 333.69, 718.88, 747.86, 470.5, 553.11, 499.46, 707.9, 358.31, 484.18, 478.2, 449.53, 558.5, 432.28, 456.6, 696.2, 431.9, 346.64, 463.7, 441.32, 502.95, 568.39, 366.83, 408.03, 507.52, 779.73, 348.62, 391.21, 436.93, 565.06, 476.37, 527.42, 408.64, 551.25, 345.7, 335.79, 375.71, 563.82, 347.72, 444.88, 367.72, 478.56, 407.1, 547.7, 374.96, 342.95, 353.91, 581.06, 539.09, 372.27, 470.25, 479.84, 387.48, 367.99, 375.14, 480.49, 517.9, 500.71, 335.19, 530.95, 468.93, 432.76, 445.32, 601.91, 512.16, 739.48, 379.98, 333.85, 338.52, 546.32, 425.55, 496.77, 397.84, 387.5, 575.29, 522.49, 350.06, 567.31, 344.18, 368.73, 382.51, 400.75, 354.94, 455.94, 395.2, 335.05, 363.11, 503.14, 699.15, 525.71, 351.74, 339.52, 379.02, 457.25, 358.15, 529.02, 371.08, 602.66, 382.42, 440.42, 559.26, 375.97, 400.63, 460.56, 458.57, 437.11, 380.08, 386.92, 489.45, 470.73, 473.06, 349.39, 404.51, 411.7, 390.16, 355.17, 348.27, 528.87, 478.6, 496.17, 364.44, 432.53, 352.31, 428.84, 365.27, 384.56, 500.75, 442.33, 334.31, 516.03, 527.36, 443.3, 473.38, 352.42, 414.38, 347.63, 477.75, 445.02, 409.03, 533.19, 369.33, 349.17, 566.37, 503.41, 410.66, 379.87, 345.47, 478.57, 654.46, 349.56, 441.26, 394.46, 394.55, 366.84, 378.16, 528.05, 388.19, 638.12, 401.87, 377.07, 499.62, 379.64, 542.67, 454.41, 381.79, 419.49, 344.32, 502.44, 701.38, 357.2, 493.76, 404.21, 420.25, 373.73, 481.57, 65.0, 65.0, 64.3, 65.0, 64.3, 65.0, 64.8, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 64.9, 65.0, 65.0, 64.8, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0, 64.7, 65.0, 65.0, 65.0, 64.8, 65.0, 64.3, 65.0, 65.0, 65.0, 65.0, 65.0, 65.0]
Total number of outliers in Soil_Moisture_Percent :  565
____________________________________________________________________________________________________

# removing the outliers from the data set

In [32]:
# Removing the outliers from the Rainfall data 
Q1 = df["Rainfall_mm"].quantile(0.25)
Q3 = df["Rainfall_mm"].quantile(0.75)
IQR = Q3 - Q1
print("Inter Quartile Range : ", IQR.round(3))
lower_bound = Q1 - (1.5* IQR)
print("Lower bound : ",lower_bound)
upper_bound = Q3 + (1.5 * IQR)
print("Upper bound : ",upper_bound)

outlier_Mask = ((df["Rainfall_mm"] < lower_bound)| (df["Rainfall_mm"] > upper_bound))
print("Total Outliers in Rainfall data : ", outlier_Mask.sum())

df_cleaned = df.loc[~outlier_Mask].copy()
# Compare results
print("Original rows:", len(df))
print("Cleaned rows:", len(df_cleaned))
print("Rows removed:", len(df) - len(df_cleaned))

Inter Quartile Range :  50.6
Lower bound :  -45.10000000000001
Upper bound :  157.3
Total Outliers in Rainfall data :  300
Original rows: 10000
Cleaned rows: 9700
Rows removed: 300

# Removing the outliers from the whole data set

In [33]:

def remove_outliers(df):
    numeric_cols = df.select_dtypes(include=np.number).columns

    outlier_mask = pd.Series(False, index=df.index)

    for col in numeric_cols:
        Q1 = df[col].quantile(0.25)
        Q3 = df[col].quantile(0.75)

        IQR = Q3 - Q1

        lower_bound = Q1 - (1.5 * IQR)
        upper_bound = Q3 + (1.5 * IQR)

        col_outliers = (
            (df[col] < lower_bound) |
            (df[col] > upper_bound)
        )

        print(f"{col}: {col_outliers.sum()} outliers")

        outlier_mask = outlier_mask | col_outliers

    df_cleaned = df.loc[~outlier_mask].copy()

    print("\nOriginal rows:", len(df))
    print("Cleaned rows:", len(df_cleaned))
    print("Rows removed:", outlier_mask.sum())

    return df_cleaned

df_cleaned = remove_outliers(df)

Temperature_C: 68 outliers
Rainfall_mm: 300 outliers
Irrigation_mm: 0 outliers
Water_Used_Liters: 52 outliers
Area_Hectares: 0 outliers
Crop_Yield_Tons: 1156 outliers
Soil_Moisture_Percent: 95 outliers

Original rows: 10000
Cleaned rows: 8472
Rows removed: 1528

In [ ]:
df.to_csv("cleaned_agricultural_data.csv", index=False)

(10000, 11)