# Data cleaning

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("/home/jawad/my_jupyter_env/Data_Science_Projects/agricultural_water_efficiency/agricultural_water_efficiency_10000.csv")

In [3]:
df.head()

,Date,Region,Crop_Type,Temperature_C,Rainfall_mm,Irrigation_mm,Water_Used_Liters,Area_Hectares,Crop_Yield_Tons,Soil_Moisture_Percent,Irrigation_Method
0,2018-08-28,Buner,Wheat,11.7,86.2,254.0,25208820,7.41,17.64,44.0,Sprinkler
1,2024-09-04,Charsadda,Maize,19.1,193.4,248.8,4289340,0.97,5.69,59.1,Drip
2,2021-08-30,Peshawar,Sugarcane,18.0,39.8,214.6,20682720,8.13,311.62,41.9,Sprinkler
3,2024-12-05,Mardan,Wheat,20.3,164.8,237.4,37404600,9.30,27.34,58.9,Flood
4,2020-11-26,Mardan,Wheat,27.1,36.2,263.2,27245400,9.10,21.93,30.4,Sprinkler

In [4]:

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   Date                   10000 non-null  str
 1   Region                 10000 non-null  str
 2   Crop_Type              10000 non-null  str
 3   Temperature_C          10000 non-null  float64
 4   Rainfall_mm            9920 non-null   float64
 5   Irrigation_mm          9920 non-null   float64
 6   Water_Used_Liters      10000 non-null  int64
 7   Area_Hectares          10000 non-null  float64
 8   Crop_Yield_Tons        10000 non-null  float64
 9   Soil_Moisture_Percent  9920 non-null   float64
 10  Irrigation_Method      10000 non-null  str
dtypes: float64(6), int64(1), str(4)
memory usage: 859.5 KB

In [5]:
df.describe()

,Temperature_C,Rainfall_mm,Irrigation_mm,Water_Used_Liters,Area_Hectares,Crop_Yield_Tons,Soil_Moisture_Percent
count,10000.000000,9920.000000,9920.000000,1.000000e+04,10000.000000,10000.000000,9920.000000
mean,24.967530,60.729627,223.671119,1.773452e+07,6.244467,43.597414,39.713982
std,7.024698,40.499007,72.400188,1.102241e+07,3.297981,96.656083,8.194622
min,5.000000,0.200000,40.000000,3.948800e+05,0.500000,0.420000,11.600000
25%,20.300000,30.800000,174.600000,8.661810e+06,3.397500,7.380000,34.200000
50%,25.000000,51.900000,224.600000,1.626726e+07,6.260000,14.080000,39.500000
75%,29.700000,81.400000,273.000000,2.505015e+07,9.070000,24.272500,45.025000
max,44.000000,260.000000,420.000000,6.572970e+07,12.000000,848.070000,65.000000

In [6]:
# total duplicate value in the data set 
sum_of_dup = df.duplicated().sum()
print("\nsum of the duplicated rows in the data set : ",sum_of_dup)
print("__"*45)


# tota null value in the data set 
total_null_value = df.isnull().sum()
print("\ntotal null value in the data set : \n", total_null_value)
print("__"*45)

# filling the null value in the data set 
df["Region"] = df["Region"].fillna(df["Region"].mode()[0])
df["Crop_Type"] = df["Crop_Type"].fillna(df["Crop_Type"].mode()[0])
df["Rainfall_mm"] = df["Rainfall_mm"].fillna(df["Rainfall_mm"].median())
df["Irrigation_mm"] = df["Irrigation_mm"].fillna(df["Irrigation_mm"].median())



# checking the data types of the data 
data_types = df.dtypes
print("\nData types of the columns : \n",data_types)
print("__"* 45)

# converting the data type of the date column into correct formate 
df["Date"] = pd.to_datetime(df["Date"])
print("Data type of the date columns : ",df["Date"].dtypes)
print("__"* 45)

# droping duplicates rows from the data set 
df = df.drop_duplicates()

sum of the duplicated rows in the data set :  0
__________________________________________________________________________________________

total null value in the data set :
 Date                      0
Region                    0
Crop_Type                 0
Temperature_C             0
Rainfall_mm              80
Irrigation_mm            80
Water_Used_Liters         0
Area_Hectares             0
Crop_Yield_Tons           0
Soil_Moisture_Percent    80
Irrigation_Method         0
dtype: int64
__________________________________________________________________________________________

Data types of the columns :
 Date                         str
Region                       str
Crop_Type                    str
Temperature_C            float64
Rainfall_mm              float64
Irrigation_mm            float64
Water_Used_Liters          int64
Area_Hectares            float64
Crop_Yield_Tons          float64
Soil_Moisture_Percent    float64
Irrigation_Method            str
dtype: object
__________________________________________________________________________________________
Data type of the date columns :  datetime64[us]
__________________________________________________________________________________________

In [7]:
df.to_csv("clean_data.csv",index = False)