# Data cleaning

In [2]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("/home/jawad/my_jupyter_env/Data_Science_Projects/Urban-Road-Safety-Near-Miss-Analysis/urban_near_miss_dataset_12000.csv")

In [4]:
df.head()

,Record_ID,City,Day_of_Week,Hour,Weather,Traffic_Level,Vehicle_Type,Road_Type,Speed_Limit_kmh,Average_Speed_kmh,Pedestrian_Count,Visibility_Percent,Near_Miss_Score,Incident
0,1,Peshawar,Thursday,6,Cloudy,Medium,Motorcycle,Main Road,60,51.7,11,82.3,40.2,0
1,2,Karachi,Friday,19,Clear,Medium,Bus,Residential,50,51.8,10,91.1,31.6,0
2,3,Rawalpindi,Friday,14,Clear,Medium,Rickshaw,Residential,50,74.7,11,82.2,44.8,0
3,4,Peshawar,Sunday,10,Rain,High,Car,Main Road,60,39.4,7,74.0,35.6,0
4,5,Rawalpindi,Saturday,7,Rain,Severe,Rickshaw,Highway,100,62.5,8,97.3,57.1,1

In [5]:
# null value in the data set 
print(df.isnull().sum())
print("*"*45)

# check duplicates rows in the data set 
print(df.duplicated().sum())
print("*"*45)

# checking the data types of the columns
print(df.dtypes)
print("*"*45)

# checking the hours in the correct formate or not 
print(df["Hour"].between(0,23).all())
print("*"*45)

print(df["Hour"].between(0,100).all())

Record_ID             0
City                  0
Day_of_Week           0
Hour                  0
Weather               0
Traffic_Level         0
Vehicle_Type          0
Road_Type             0
Speed_Limit_kmh       0
Average_Speed_kmh     0
Pedestrian_Count      0
Visibility_Percent    0
Near_Miss_Score       0
Incident              0
dtype: int64
*********************************************
0
*********************************************
Record_ID               int64
City                      str
Day_of_Week               str
Hour                    int64
Weather                   str
Traffic_Level             str
Vehicle_Type              str
Road_Type                 str
Speed_Limit_kmh         int64
Average_Speed_kmh     float64
Pedestrian_Count        int64
Visibility_Percent    float64
Near_Miss_Score       float64
Incident                int64
dtype: object
*********************************************
True
*********************************************
True

# Basic Analysis

In [9]:
# what is the average speed .
avg_speed = df["Average_Speed_kmh"].mean()
print("Average speed : ",avg_speed)

# median speed 
med_speed = df["Average_Speed_kmh"].median()
print("median speed : ",med_speed)

# highest speed
high_speed = df["Average_Speed_kmh"].max()
print("highest speed : ",high_speed)

# standard deviation of near miss score 
miss_score_std = df["Near_Miss_Score"].std()
print("Near miss score standard deviation : ",miss_score_std.round(3))

# what is the percentage obeservation had in incident.
total_observation = len(df)
print("total observation : ",total_observation)
incident_observation = df["Incident"].sum()
print("Incident observation : ",incident_observation)
percentage_of_incident_obser = (incident_observation / total_observation ) * 100
print("total percentage of the incident observation : ",percentage_of_incident_obser.round(3))

Average speed :  47.459875
median speed :  44.0
highest speed :  120.0
Near miss score standard deviation :  15.585
total observation :  12000
Incident observation :  2018
total percentage of the incident observation :  16.817

# City analysis

In [ ]:
# how many observation from each city ?
ob_each_city = df["City"].value_counts()
print("observation of each city : ",ob_each_city)
print("*" * 50)


# which city has the most incident ?
incident = df.groupby("City")["Incident"].sum()
most_incident = incident.idxmax()
print("\nmost incident city : ",most_incident)
print("*" * 50)


# which city has the highest average  near miss score ?
miss_score = df.groupby("City")["Near_Miss_Score"].mean()
print("\nNear miss score : ",miss_score)
highest_avg_miss_score = miss_score.idxmax()
print("\nhighest average near miss score : ",highest_avg_miss_score )
print("*" * 50)

# which city has the lowest incident rate ?
incident_rate = df.groupby("City")["Incident"].mean() * 100
print("incident rate of all city : ",incident_rate)
print("*" * 50)

lowest_incident_Rate = incident_rate.idxmin()
print("lowest incident rate of the city : ",lowest_incident_Rate)

observation of each city :  City
Karachi       1779
Multan        1734
Rawalpindi    1732
Quetta        1704
Peshawar      1702
Islamabad     1692
Lahore        1657
Name: count, dtype: int64
**************************************************

most incident city :  Multan
**************************************************

Near miss score :  City
Islamabad     40.851537
Karachi       40.450422
Lahore        41.356488
Multan        40.992445
Peshawar      40.598472
Quetta        41.170599
Rawalpindi    40.850289
Name: Near_Miss_Score, dtype: float64

highest average near miss score :  Lahore
**************************************************
incident rate of all city :  City
Islamabad     17.080378
Karachi       16.245082
Lahore        16.535908
Multan        18.512111
Peshawar      16.098707
Quetta        16.314554
Rawalpindi    16.916859
Name: Incident, dtype: float64
**************************************************
lowest incident rate of the city :  Peshawar

In [10]:
df

,Record_ID,City,Day_of_Week,Hour,Weather,Traffic_Level,Vehicle_Type,Road_Type,Speed_Limit_kmh,Average_Speed_kmh,Pedestrian_Count,Visibility_Percent,Near_Miss_Score,Incident
0,1,Peshawar,Thursday,6,Cloudy,Medium,Motorcycle,Main Road,60,51.7,11,82.3,40.2,0
1,2,Karachi,Friday,19,Clear,Medium,Bus,Residential,50,51.8,10,91.1,31.6,0
2,3,Rawalpindi,Friday,14,Clear,Medium,Rickshaw,Residential,50,74.7,11,82.2,44.8,0
3,4,Peshawar,Sunday,10,Rain,High,Car,Main Road,60,39.4,7,74.0,35.6,0
4,5,Rawalpindi,Saturday,7,Rain,Severe,Rickshaw,Highway,100,62.5,8,97.3,57.1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,11996,Quetta,Tuesday,19,Cloudy,Medium,Motorcycle,Market,50,37.3,31,74.5,37.9,0
11996,11997,Peshawar,Thursday,18,Rain,Severe,Rickshaw,Residential,50,22.7,10,84.4,76.3,1
11997,11998,Lahore,Sunday,13,Clear,Low,Van,Residential,50,41.7,8,98.3,20.8,0
11998,11999,Rawalpindi,Monday,1,Clear,Medium,Bus,Market,50,41.8,25,87.0,25.9,0
11999,12000,Karachi,Friday,4,Clear,Medium,Van,Residential,50,27.9,3,92.5,41.5,0