# understanding data

In [1]:
import  numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [4]:
df = df = pd.read_csv("/home/jawad/my_jupyter_env/Data_Science_Projects/Urban-Road-Safety-Near-Miss-Analysis/urban_near_miss_dataset_12000.csv")
df

,Record_ID,City,Day_of_Week,Hour,Weather,Traffic_Level,Vehicle_Type,Road_Type,Speed_Limit_kmh,Average_Speed_kmh,Pedestrian_Count,Visibility_Percent,Near_Miss_Score,Incident
0,1,Peshawar,Thursday,6,Cloudy,Medium,Motorcycle,Main Road,60,51.7,11,82.3,40.2,0
1,2,Karachi,Friday,19,Clear,Medium,Bus,Residential,50,51.8,10,91.1,31.6,0
2,3,Rawalpindi,Friday,14,Clear,Medium,Rickshaw,Residential,50,74.7,11,82.2,44.8,0
3,4,Peshawar,Sunday,10,Rain,High,Car,Main Road,60,39.4,7,74.0,35.6,0
4,5,Rawalpindi,Saturday,7,Rain,Severe,Rickshaw,Highway,100,62.5,8,97.3,57.1,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11995,11996,Quetta,Tuesday,19,Cloudy,Medium,Motorcycle,Market,50,37.3,31,74.5,37.9,0
11996,11997,Peshawar,Thursday,18,Rain,Severe,Rickshaw,Residential,50,22.7,10,84.4,76.3,1
11997,11998,Lahore,Sunday,13,Clear,Low,Van,Residential,50,41.7,8,98.3,20.8,0
11998,11999,Rawalpindi,Monday,1,Clear,Medium,Bus,Market,50,41.8,25,87.0,25.9,0
11999,12000,Karachi,Friday,4,Clear,Medium,Van,Residential,50,27.9,3,92.5,41.5,0

In [3]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 12000 entries, 0 to 11999
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Record_ID           12000 non-null  int64
 1   City                12000 non-null  str
 2   Day_of_Week         12000 non-null  str
 3   Hour                12000 non-null  int64
 4   Weather             12000 non-null  str
 5   Traffic_Level       12000 non-null  str
 6   Vehicle_Type        12000 non-null  str
 7   Road_Type           12000 non-null  str
 8   Speed_Limit_kmh     12000 non-null  int64
 9   Average_Speed_kmh   12000 non-null  float64
 10  Pedestrian_Count    12000 non-null  int64
 11  Visibility_Percent  12000 non-null  float64
 12  Near_Miss_Score     12000 non-null  float64
 13  Incident            12000 non-null  int64
dtypes: float64(3), int64(5), str(6)
memory usage: 1.3 MB

In [5]:
df.describe()

,Record_ID,Hour,Speed_Limit_kmh,Average_Speed_kmh,Pedestrian_Count,Visibility_Percent,Near_Miss_Score,Incident
count,12000.00000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000,12000.000000
mean,6000.50000,11.588333,60.221667,47.459875,13.757333,82.157433,40.891392,0.168167
std,3464.24595,6.945302,18.755804,23.654891,10.206671,15.439919,15.585453,0.374030
min,1.00000,0.000000,40.000000,10.000000,0.000000,20.000000,0.000000,0.000000
25%,3000.75000,6.000000,50.000000,30.400000,7.000000,76.200000,30.200000,0.000000
50%,6000.50000,12.000000,50.000000,44.000000,9.000000,86.100000,40.600000,0.000000
75%,9000.25000,18.000000,60.000000,59.900000,19.000000,93.000000,51.300000,0.000000
max,12000.00000,23.000000,100.000000,120.000000,57.000000,100.000000,100.000000,1.000000

In [6]:
df.dtypes

Record_ID               int64
City                      str
Day_of_Week               str
Hour                    int64
Weather                   str
Traffic_Level             str
Vehicle_Type              str
Road_Type                 str
Speed_Limit_kmh         int64
Average_Speed_kmh     float64
Pedestrian_Count        int64
Visibility_Percent    float64
Near_Miss_Score       float64
Incident                int64
dtype: object

* Which columns are numerical?
* Which columns are categorical?
* What is the average speed?
* What is the average near-miss score?
* What is the maximum pedestrian count?
* What is the minimum visibility?