# Digital Lifestyle, Productivity & Screen Behavior Analysis

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv("digital_lifestyle_productivity_7000.csv")
df

,User_ID,Date,Age,Occupation,Sleep_Hours,Sleep_Quality,Screen_Time_Hours,Social_Media_Hours,Study_Work_Hours,Exercise_Minutes,Notifications_Received,Phone_Pickups,Caffeine_Cups,Stress_Score,Mood_Score,Productivity_Score,Tasks_Planned,Tasks_Completed,Weekend
0,U02207,2025-01-01,28,Analyst,6.3,8.0,6.5,2.0,10.7,42,145,94,1,4,9.0,100.0,8,4,No
1,U02443,2025-01-01,27,Teacher,7.0,8.0,6.7,1.7,9.0,15,114,87,0,6,8.0,89.1,6,2,No
2,U01081,2025-01-01,19,Freelancer,5.0,7.0,5.7,2.1,8.3,48,123,59,0,5,10.0,75.6,10,5,Yes
3,U02967,2025-01-01,28,Software Engineer,6.6,10.0,3.9,2.3,7.0,23,98,81,1,3,9.0,84.1,8,7,Yes
4,U03240,2025-01-01,49,Teacher,6.1,9.0,4.1,2.5,7.5,43,64,64,4,3,10.0,90.2,12,7,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6995,U02989,2025-12-31,22,Freelancer,7.2,10.0,3.7,0.5,11.7,18,47,43,0,5,10.0,100.0,11,6,No
6996,U02667,2025-12-31,45,Freelancer,6.8,10.0,8.2,4.7,6.6,61,174,113,1,6,9.0,62.2,7,4,No
6997,U04676,2025-12-31,32,Software Engineer,6.9,10.0,3.5,1.4,9.8,19,115,54,1,4,8.0,94.0,5,5,No
6998,U03156,2025-12-31,42,Teacher,7.4,8.0,8.0,3.2,8.9,14,151,94,2,5,9.0,88.6,5,5,No
6999,U00617,2025-12-31,48,Teacher,5.1,7.0,5.6,3.0,8.2,10,146,68,1,8,6.0,77.2,9,6,No

In [6]:
df.head()

,User_ID,Date,Age,Occupation,Sleep_Hours,Sleep_Quality,Screen_Time_Hours,Social_Media_Hours,Study_Work_Hours,Exercise_Minutes,Notifications_Received,Phone_Pickups,Caffeine_Cups,Stress_Score,Mood_Score,Productivity_Score,Tasks_Planned,Tasks_Completed,Weekend
0,U02207,2025-01-01,28,Analyst,6.3,8.0,6.5,2.0,10.7,42,145,94,1,4,9.0,100.0,8,4,No
1,U02443,2025-01-01,27,Teacher,7.0,8.0,6.7,1.7,9.0,15,114,87,0,6,8.0,89.1,6,2,No
2,U01081,2025-01-01,19,Freelancer,5.0,7.0,5.7,2.1,8.3,48,123,59,0,5,10.0,75.6,10,5,Yes
3,U02967,2025-01-01,28,Software Engineer,6.6,10.0,3.9,2.3,7.0,23,98,81,1,3,9.0,84.1,8,7,Yes
4,U03240,2025-01-01,49,Teacher,6.1,9.0,4.1,2.5,7.5,43,64,64,4,3,10.0,90.2,12,7,No

In [ ]:
print(df.describe())

               Age  Sleep_Hours  Sleep_Quality  Screen_Time_Hours  \
count  7000.000000  7000.000000    6965.000000        7000.000000
mean     39.045714     7.002443       9.067767           6.507271
std      12.244902     1.200371       1.281132           2.174549
min      18.000000     3.000000       3.000000           1.000000
25%      29.000000     6.200000       8.000000           5.000000
50%      39.000000     7.000000      10.000000           6.500000
75%      50.000000     7.800000      10.000000           8.000000
max      60.000000    10.000000      10.000000          14.000000

       Social_Media_Hours  Study_Work_Hours  Exercise_Minutes  \
count         6965.000000       7000.000000       7000.000000
mean             2.603604          8.529614         39.852143
std              1.414123          1.973106         27.139193
min              0.000000          1.400000          1.000000
25%              1.500000          7.200000         20.000000
50%              2.400000          8.600000         34.000000
75%              3.500000          9.900000         53.000000
max              9.200000         12.000000        180.000000

       Notifications_Received  Phone_Pickups  Caffeine_Cups  Stress_Score  \
count             7000.000000    7000.000000    7000.000000   7000.000000
mean               124.317000      84.686286       1.702857      4.590714
std                 39.390378      29.229382       1.288166      1.844211
min                  5.000000       3.000000       0.000000      1.000000
25%                 98.000000      65.000000       1.000000      3.000000
50%                123.000000      84.000000       2.000000      5.000000
75%                150.000000     104.000000       2.000000      6.000000
max                300.000000     189.000000       8.000000     10.000000

        Mood_Score  Productivity_Score  Tasks_Planned  Tasks_Completed
count  6965.000000         7000.000000    7000.000000      7000.000000
mean      8.392965           84.071043       7.068571         4.284857
std       1.421074           14.076301       2.625152         2.081632
min       3.000000           32.700000       2.000000         0.000000
25%       7.000000           74.575000       5.000000         3.000000
50%       9.000000           86.100000       7.000000         4.000000
75%      10.000000           97.500000       9.000000         6.000000
max      10.000000          100.000000      20.000000        13.000000

In [ ]:
print(df.shape)
print("\n",df.info())
print(df.dtypes)
print(df.isnull().sum())

(7000, 19)
<class 'pandas.DataFrame'>
RangeIndex: 7000 entries, 0 to 6999
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   User_ID                 7000 non-null   str
 1   Date                    7000 non-null   str
 2   Age                     7000 non-null   int64
 3   Occupation              7000 non-null   str
 4   Sleep_Hours             7000 non-null   float64
 5   Sleep_Quality           6965 non-null   float64
 6   Screen_Time_Hours       7000 non-null   float64
 7   Social_Media_Hours      6965 non-null   float64
 8   Study_Work_Hours        7000 non-null   float64
 9   Exercise_Minutes        7000 non-null   int64
 10  Notifications_Received  7000 non-null   int64
 11  Phone_Pickups           7000 non-null   int64
 12  Caffeine_Cups           7000 non-null   int64
 13  Stress_Score            7000 non-null   int64
 14  Mood_Score              6965 non-null   float64
 15  Productivity_Score      7000 non-null   float64
 16  Tasks_Planned           7000 non-null   int64
 17  Tasks_Completed         7000 non-null   int64
 18  Weekend                 7000 non-null   str
dtypes: float64(7), int64(8), str(4)
memory usage: 1.0 MB

 None
User_ID                       str
Date                          str
Age                         int64
Occupation                    str
Sleep_Hours               float64
Sleep_Quality             float64
Screen_Time_Hours         float64
Social_Media_Hours        float64
Study_Work_Hours          float64
Exercise_Minutes            int64
Notifications_Received      int64
Phone_Pickups               int64
Caffeine_Cups               int64
Stress_Score                int64
Mood_Score                float64
Productivity_Score        float64
Tasks_Planned               int64
Tasks_Completed             int64
Weekend                       str
dtype: object
User_ID                    0
Date                       0
Age                        0
Occupation                 0
Sleep_Hours                0
Sleep_Quality             35
Screen_Time_Hours          0
Social_Media_Hours        35
Study_Work_Hours           0
Exercise_Minutes           0
Notifications_Received     0
Phone_Pickups              0
Caffeine_Cups              0
Stress_Score               0
Mood_Score                35
Productivity_Score         0
Tasks_Planned              0
Tasks_Completed            0
Weekend                    0
dtype: int64

*  35 values are missing in sleep quality column
*  35 values are missing in Social media hours 
*  35 values are missing in mood score
*  the Date column data type are incorrect

In [31]:
df.duplicated().sum()
df = df.drop_duplicates()

# Data cleaning

In [24]:
df["Sleep_Quality"] = df["Sleep_Quality"].fillna(df["Sleep_Quality"].median())
df["Social_Media_Hours"] = df["Social_Media_Hours"].fillna(df["Social_Media_Hours"].median())
df["Mood_Score"] = df["Mood_Score"].fillna(df["Mood_Score"].median())
print(df.isnull().sum())

User_ID                   0
Date                      0
Age                       0
Occupation                0
Sleep_Hours               0
Sleep_Quality             0
Screen_Time_Hours         0
Social_Media_Hours        0
Study_Work_Hours          0
Exercise_Minutes          0
Notifications_Received    0
Phone_Pickups             0
Caffeine_Cups             0
Stress_Score              0
Mood_Score                0
Productivity_Score        0
Tasks_Planned             0
Tasks_Completed           0
Weekend                   0
dtype: int64